mod schema;
mod transport;
mod validation;

use crate::error::PlanError;

pub use schema::{
    AIDER_MODEL_METADATA_PLACEHOLDER, AIDER_MODEL_SETTINGS_PLACEHOLDER,
    ARTIFACT_PLACEHOLDER_PREFIX, ArtifactLifecycle, BRIDGE_BASE_URL_PLACEHOLDER,
    CLAUDE_AVAILABLE_MODELS_PLACEHOLDER, CLAUDE_MODEL_PICKER_PLACEHOLDER,
    CLAUDE_MODEL_PRESENTATIONS_PLACEHOLDER, CLINE_MODEL_CATALOG_PLACEHOLDER,
    CODEX_HOME_ARTIFACT_PLACEHOLDER, CODEX_HOME_OVERLAY_ID, CODEX_HOME_PLACEHOLDER,
    CODEX_MODEL_CATALOG_PLACEHOLDER, CODEX_PROFILE_ARTIFACT_ID, CleanupPolicy,
    ConfigurationOverlay, DEEPSEEK_MODEL_CATALOG_PLACEHOLDER, EnvironmentOverlay,
    FX_GATEWAY_CHAT_URL_PLACEHOLDER, GOOSE_ADDITIONAL_CONFIG_FILES_PLACEHOLDER,
    GOOSE_MODEL_CATALOG_PLACEHOLDER, HERMES_MODEL_CATALOG_PLACEHOLDER,
    KIMI_CODE_MODEL_CATALOG_PLACEHOLDER, LaunchId, LaunchPlan, LaunchScopedFile,
    NAN_SEARCH_BLOCK_BEGIN, NAN_SEARCH_BLOCK_END, OPENCLAW_MODEL_ALIASES_PLACEHOLDER,
    OPENCLAW_MODEL_CATALOG_PLACEHOLDER, OPENCODE_MODEL_CATALOG_PLACEHOLDER, ObservabilityFormat,
    ObservabilityPolicy, OverlayFile, OverlayFilePolicy, PI_MODEL_CATALOG_PLACEHOLDER,
    PROVIDER_BASE_URL_PLACEHOLDER, ProcessSpec, QWEN_CODE_MODEL_CATALOG_PLACEHOLDER,
    SELECTED_MODEL_CAPABILITIES_PLACEHOLDER, SELECTED_MODEL_CONTEXT_WINDOW_PLACEHOLDER,
    SELECTED_MODEL_DISPLAY_NAME_PLACEHOLDER, SELECTED_MODEL_MAX_OUTPUT_TOKENS_PLACEHOLDER,
    SELECTED_MODEL_REASONING_EFFORT_PLACEHOLDER, TemporaryArtifact, TemporaryArtifactKind,
    TemporaryArtifactMode, TerminalMode, USER_HOME_PLACEHOLDER, WebSearchPolicy,
};
pub use transport::{ListenAddress, Protocol, Transport, TransportKind};

pub struct LaunchPlanValidator;

impl LaunchPlanValidator {
    /// Checks all schema version 2 launch-plan invariants.
    ///
    /// # Errors
    ///
    /// Returns [`PlanError`] for the first invalid or unsafe field.
    pub fn validate(plan: &LaunchPlan) -> Result<(), PlanError> {
        validation::validate(plan)
    }
}
