// Spanish site copy for nan-harness. This classic script runs before
// app.js and only builds strings: it reads no DOM, storage, or navigator state.
// The caller passes every link and command the copy interpolates.
function nanHarnessContentEs({ harnessLink, nanLink, unixInstallCommand, windowsInstallCommand }) {
  return {
    siteTitle: 'nan-harness — todos los harness con NaN',
    siteMeta: 'Usa agentes de código compatibles con NaN mediante nan-harness.',
    docsTitle: 'nan-harness — documentación',
    docsMeta: 'Documentación para ejecutar agentes de código compatibles con NaN mediante nan-harness.',
    logosTitle: 'nan-harness — aviso sobre logos',
    logosMeta: 'Aviso sobre logos de nan-harness.',
    language: 'Idioma',
    homeAria: 'Inicio de nan-harness',
    mainNavigation: 'Navegación principal',
    docsNavigation: 'Navegación de la documentación',
    breadcrumb: 'Ruta de navegación',
    skipToContent: 'Saltar al contenido',
    docs: 'DOCUMENTACIÓN',
    faq: 'FAQ',
    getStarted: 'EMPEZAR',
    githubAria: 'Abrir nan-harness en GitHub',
    readDocs: 'Documentación',
    seeHarnesses: 'VER HARNESSES COMPATIBLES',
    heroTitle: 'TODOS|LOS HARNESSES|CON NAN.',
    heroLede: `Ejecuta cualquier agente de código compatible con ${nanLink('NaN')} mediante nan-harness. Un solo comando comprueba la compatibilidad, descubre tus modelos disponibles, prepara la conexión y supervisa el proceso.`,
    whatIs: 'QUÉ ES NAN-HARNESS',
    oneLocal: 'El modelo se mueve.',
    everyAgent: 'Tu flujo se mantiene.',
    whatText: 'NaN proporciona los modelos. Tu agente proporciona el flujo de trabajo. nan-harness los conecta a través de todos los harness compatibles, mientras conservas el cliente y el flujo de trabajo que ya utilizas.',
    howItWorks: 'VER EL FLUJO',
    workflowLabel: 'LA FORMA RECOMENDADA',
    discovering: '→ descubriendo harness',
    startingRoute: '→ iniciando ruta local',
    ready: '→ harness listo',
    workflowHeading: 'Arráncalo con nan-harness.',
    workflowSubheading: 'Un comando.',
    workflowText: 'Usa <code>nanh &lt;harness&gt;</code> para el uso diario. Comprueba la compatibilidad, descubre tus modelos disponibles de NaN, prepara los bridges necesarios y supervisa el proceso. Usa <code>nanh config &lt;harness&gt;</code> solo cuando necesites arrancar el harness directamente; actualiza esa configuración si cambian tu clave guardada o el catálogo de modelos.',
    workflowMode: 'recomendado / avanzado',
    managedLaunchResult: '→ recomendado: comprueba, conecta y supervisa OpenCode',
    nativeSetupResult: '→ avanzado: escribe configuración persistente en OpenCode',
    directLaunchResult: '→ lanzamiento directo: usa credenciales copiadas y un catálogo de modelos',
    telemetryLabel: 'PRIVACIDAD POR DISEÑO',
    telemetryHeading: 'Telemetría apagada.',
    telemetrySubheading: 'Con tu consentimiento.',
    telemetryCommand: 'nanh telemetry on',
    telemetryText: 'La telemetría está desactivada por defecto. Si la activas, nan-harness envía diagnósticos sanitizados y datos de uso mínimos. Nunca incluye prompts, respuestas del modelo, argumentos, rutas ni credenciales. Un diagnóstico específico de un modelo puede incluir su identificador de NaN.',
    telemetryPanelTitle: 'nanh telemetry',
    faqHeading: 'CONVIENE|SABER.',
    finalAgent: 'CADA AGENTE.',
    finalNan: 'CON RUTA NAN.',
    startDocs: 'Comienza leyendo la documentación',
    installLatest: 'INSTALAR LA ÚLTIMA VERSIÓN',
    installCommand: unixInstallCommand,
    installWindowsCommand: windowsInstallCommand,
    installPlatform: 'Elige tu sistema operativo',
    unixTab: 'macOS / LINUX',
    windowsTab: 'WINDOWS',
    copy: 'Copiar',
    chooseHarness: 'Elige un harness',
    oneRoute: 'UNA RUTA · CADA HARNESS',
    copyCommand: 'Copiar comando',
    copyingCommand: 'Copiando comando',
    commandCopied: 'Comando copiado',
    pauseCarousel: 'Pausar selección automática',
    resumeCarousel: 'Reanudar selección automática',
    footerTagline: 'Todos los harnesses. Tu proveedor favorito.',
    logoNotices: 'Aviso sobre logos',
    logosHeading: 'Aviso sobre logos',
    logosIntro: 'Estos recursos identifican productos de terceros compatibles. Su inclusión no implica patrocinio, respaldo ni relación alguna. Los nombres y las marcas registradas siguen siendo propiedad de sus respectivos titulares y no están cubiertos por la licencia Apache-2.0 de este repositorio.',
    logosSimpleIconsHeading: 'Simple Icons 16.28.0',
    logosSimpleIconsText: '<code>claude.svg</code>, <code>opencode.svg</code>, <code>pi.svg</code>, <code>deepseek.svg</code>, <code>cline.svg</code>, <code>qwen.svg</code> y <code>kimi.svg</code> proceden del paquete npm <code>simple-icons</code> versión 16.28.0. Simple Icons publica los datos de sus iconos bajo CC0-1.0. La licencia y el aviso sobre marcas están incluidos en <a href="logos/licenses/CC0-1.0.txt">licenses/CC0-1.0.txt</a> y <a href="logos/licenses/SIMPLE-ICONS-DISCLAIMER.md">licenses/SIMPLE-ICONS-DISCLAIMER.md</a>.',
    logosPackage: 'Paquete: <a href="https://www.npmjs.com/package/simple-icons/v/16.28.0" target="_blank" rel="noreferrer">simple-icons 16.28.0 en npm</a>',
    logosOfficialHeading: 'Fuentes oficiales de los proyectos',
    logosOfficialText: 'El resto de las marcas procede de las fuentes oficiales de cada proyecto que aparecen a continuación. Se incluyen únicamente para identificar los productos compatibles.',
    logosTableHeaders: ['Recurso', 'Fuente', 'Términos'],
    logosSources: [
      ['codex.png', '<a href="https://marketplace.visualstudio.com/items?itemName=OpenAI.chatgpt" target="_blank" rel="noreferrer">Extensión oficial de Codex para VS Code 26.5818.31338</a>, usando su <a href="https://openai.gallerycdn.vsassets.io/extensions/openai/chatgpt/26.5818.31338/1787264961823/Microsoft.VisualStudio.Services.Icons.Default" target="_blank" rel="noreferrer">icono publicado</a>', '<a href="https://openai.com/brand/" target="_blank" rel="noreferrer">Directrices de marca de OpenAI</a>; el fondo negro se convirtió en transparente sin cambiar la geometría de la marca'],
      ['hermes.png', '<a href="https://github.com/NousResearch/hermes-agent/blob/06b9141109fbd320b14b8c88645ab37fc4f42c9d/apps/desktop/assets/icon.png" target="_blank" rel="noreferrer"><code>NousResearch/hermes-agent</code> en <code>06b9141</code></a>', 'MIT; extraído de la aplicación de escritorio instalada localmente y redimensionado a 256 px sin cambios visuales'],
      ['omp.svg', 'La marca de la cabecera oficial de <a href="https://omp.sh/" target="_blank" rel="noreferrer"><code>omp.sh</code></a>, recuperada el 2026-08-31', 'Usada únicamente para identificar el producto; copiada del SVG publicado en la cabecera sin cambiar su geometría ni sus colores'],
      ['prime.svg', '<a href="https://github.com/PrimeIntellect-ai/prime-agent/blob/c75a637b00d3b52762841e72efe92289a0d55b49/assets/brand/prime-butterfly.svg" target="_blank" rel="noreferrer"><code>PrimeIntellect-ai/prime-agent</code> en <code>c75a637</code></a>', 'MIT'],
      ['openclaw.svg', '<a href="https://github.com/openclaw/openclaw/blob/73ff2d2f45b26856882423d9ae87a76a727ac7cd/ui/public/favicon.svg" target="_blank" rel="noreferrer"><code>openclaw/openclaw</code> en <code>73ff2d2</code></a>', 'MIT'],
      ['aider.svg', '<a href="https://github.com/Aider-AI/aider/blob/5dc9490bb35f9729ef2c95d00a19ccd30c26339c/aider/website/assets/logo.svg" target="_blank" rel="noreferrer"><code>Aider-AI/aider</code> en <code>5dc9490</code></a>', 'Apache-2.0'],
      ['goose.svg', '<a href="https://github.com/aaif-goose/goose/blob/384b6cc0d3b52762841e72efe92289a0d55b49/documentation/static/img/goose.svg" target="_blank" rel="noreferrer"><code>aaif-goose/goose</code> en <code>384b6cc</code></a>', 'Apache-2.0'],
      ['fx.svg', 'La <a href="https://fx.sh/" target="_blank" rel="noreferrer">marca de cabecera oficial de <code>fx.sh</code></a>, asociada a <a href="https://github.com/vercel-labs/fx/tree/580a0c5da9386319741968c09c1cee69e763487a" target="_blank" rel="noreferrer"><code>vercel-labs/fx</code> en <code>580a0c5</code></a>', 'Se usa únicamente para identificar el producto; el repositorio enlazado del proyecto está bajo Apache-2.0; glifo estático extraído sin el efecto de brillo exclusivo de la web'],
    ],
    logosLicenseText: 'El texto de Apache-2.0 está incluido en <a href="logos/licenses/APACHE-2.0.txt">licenses/APACHE-2.0.txt</a>. Los avisos MIT aplicables están incluidos en archivos separados: <a href="logos/licenses/MIT-hermes-agent.txt">MIT-hermes-agent.txt</a>, <a href="logos/licenses/MIT-openclaw.txt">MIT-openclaw.txt</a> y <a href="logos/licenses/MIT-prime-agent.txt">MIT-prime-agent.txt</a>. La marca de Codex se usa únicamente para identificar el producto de OpenAI compatible y sigue sujeta a las directrices de marca de OpenAI.',
    searchDocs: 'Buscar en la documentación...',
    docsHeading: 'nan-harness',
    docsIntro: `Ejecuta con ${nanLink('NaN')} los agentes de código que ya usas, mediante nan-harness. Usa <code>nanh &lt;harness&gt;</code> para el uso diario y <code>nanh config &lt;harness&gt;</code> solo para la configuración nativa avanzada. <code>nanh</code> es el alias corto de <code>nan-harness</code>.`,
    docsNavStart: 'EMPEZAR',
    docsNavReference: 'REFERENCIA',
    docsSections: [
      ['install', 'INSTALACIÓN', [
        ['p', 'Ejecuta esto en macOS o Linux:'],
        ['code', unixInstallCommand],
        ['p', 'En Windows, desde PowerShell:'],
        ['code', windowsInstallCommand],
        ['p', 'Si te lo pide, abre una terminal nueva. Después comprueba la instalación:'],
        ['code', 'nanh --version'],
        ['p', 'El instalador proporciona <code>nan-harness</code> y <code>nanh</code>. Hay versiones para macOS, Linux y Windows. Para compilarlo desde el código fuente, consulta el <a href="https://github.com/DavidLMS/nan-harness">repositorio</a>.']
      ]],
      ['first-run', 'PRIMER USO', [
        ['p', 'Ve a tu proyecto y lanza el agente que ya usas:'],
        ['code', 'nanh claude'],
        ['p', 'Si no has definido <code>NAN_API_KEY</code>, nan-harness te pide tu API key de NaN la primera vez que la necesita. La verifica y la guarda.'],
        ['p', 'Después, usa el agente como siempre. Para elegir un modelo al arrancar, usa <code>--model</code>. Si el agente lo permite, también puedes usar su selector nativo de modelos:'],
        ['codes', ['nanh codex --model qwen3.6', 'nanh opencode --model deepseek-v4-flash']],
        ['p', 'Pasa los argumentos del agente después de <code>--</code>; nan-harness los reenvía sin modificarlos:'],
        ['codes', ['nanh codex --model qwen3.6 -- --full-auto', 'nanh claude -- --resume']],
        ['h3', 'Tu clave'],
        ['note', '<strong>Si ya tienes <code>NAN_API_KEY</code> en tu entorno, este apartado no va contigo.</strong> Esa clave manda sobre cualquier otra: nan-harness no te pedirá ninguna, no guarda nada en disco y no necesitas hacer login.'],
        ['p', 'Si no la tienes, nan-harness la guarda donde tu sistema guarda las contraseñas: Llavero en macOS, Administrador de credenciales en Windows, Secret Service en Linux. Si no hay ninguno disponible, usa un archivo privado y te avisa.'],
        ['table', ['Comando', 'Para qué sirve'], [
          ['nanh auth login', 'Introducir una clave, o cambiar la que tienes.'],
          ['nanh auth status', 'Ver qué clave se está usando y dónde está guardada.'],
          ['nanh auth logout', 'Borrar la clave guardada.']
        ]],
        ['p', 'La variable de entorno es útil en servidores y en CI. <code>nanh auth status</code> muestra qué credencial está activa:'],
        ['code', 'export NAN_API_KEY="<tu-api-key-de-NaN>"'],
        ['note', '<strong>Mantén tu clave privada.</strong> La variable de entorno nunca se copia a la configuración de un harness.']
      ]],
      ['harnesses', 'HARNESSES', [
        ['p', '<code>nanh &lt;harness&gt;</code> es la forma recomendada para todos los harness compatibles. nan-harness comprueba la versión instalada, consulta el catálogo actual de NaN, prepara los bridges necesarios y supervisa el proceso sin cambiar ajustes persistentes del proveedor. <code>nanh config &lt;harness&gt;</code> es una opción avanzada para los harnesses que admiten configuración nativa directa.'],
        ['table', ['Comando recomendado', 'Harness', 'Configuración nativa'], [
          ['nanh aider', harnessLink('Aider', 'aider'), 'opcional'],
          ['nanh cline', harnessLink('Cline', 'cline'), 'opcional'],
          ['nanh goose', harnessLink('Goose', 'goose'), 'opcional'],
          ['nanh claude', harnessLink('Claude Code', 'claude'), 'no disponible'],
          ['nanh codex', harnessLink('Codex', 'codex'), 'no disponible'],
          ['nanh opencode', harnessLink('OpenCode', 'opencode'), 'opcional'],
          ['nanh qwen', harnessLink('Qwen Code', 'qwen'), 'opcional'],
          ['nanh pi', harnessLink('Pi', 'pi'), 'opcional'],
          ['nanh kimi', harnessLink('Kimi Code', 'kimi'), 'opcional'],
          ['nanh openclaw', harnessLink('OpenClaw', 'openclaw'), 'opcional'],
          ['nanh hermes', harnessLink('Hermes Agent', 'hermes'), 'opcional'],
          ['nanh omp', harnessLink('Oh My Pi', 'omp'), 'opcional'],
          ['nanh prime-agent', harnessLink('Prime Agent', 'prime'), 'opcional'],
          ['nanh dsh', harnessLink('DeepSeek Harness', 'deepseek'), 'opcional'],
          ['nanh fx', harnessLink('fx', 'fx'), 'no disponible']
        ]],
        ['h3', 'Recomendado: ejecutar con nan-harness'],
        ['p', 'Para el uso diario, ejecuta <code>nanh &lt;harness&gt;</code>. Comprueba la versión instalada, descubre tus modelos actuales de NaN, utiliza la fuente de credenciales activa, prepara los bridges necesarios y supervisa el proceso. Si falta el harness, puede ofrecerte instalarlo.'],
        ['code', 'nanh opencode'],
        ['h3', 'Avanzado: configuración nativa'],
        ['p', 'Usa <code>nanh config &lt;harness&gt;</code> solo cuando otra herramienta o integración necesite arrancar un harness compatible mediante su ejecutable habitual. La configuración nativa escribe ajustes persistentes del proveedor. El posterior arranque se hace directamente con el harness, así que nan-harness deja de gestionar ese proceso. Este comando solo configura el harness; después, arráncalo con su ejecutable habitual:'],
        ['codes', ['nanh config opencode', 'opencode']],
        ['p', 'Claude Code, Codex y fx necesitan que nan-harness siga ejecutándose porque su conexión con NaN depende de un bridge o gateway local. Por eso no se pueden preparar para uso independiente con <code>nanh config</code>.'],
        ['p', 'La configuración nativa usa la API key guardada por <code>nanh auth login</code>; una clave que solo está en el entorno nunca se copia a otra aplicación. Usa <code>--status</code> para revisarla y <code>--refresh</code> después de cambiar la clave guardada o el catálogo de modelos. <code>--remove</code> elimina lo que añadió nan-harness y restaura los ajustes anteriores cuando puede hacerlo de forma segura.']
      ]],
      ['desktop', 'APPS DE ESCRITORIO (EXPERIMENTAL)', [
        ['p', 'Estas integraciones son <strong>experimentales</strong>. Las cinco apps se han probado en macOS. Las demás combinaciones de plataforma están cubiertas por pruebas automatizadas de compatibilidad.'],
        ['table', ['Comando', 'App', 'Disponible en'], [
          ['nanh zed', '<a href="https://zed.dev/" target="_blank" rel="noreferrer">Zed</a>', 'macOS, Windows, Linux'],
          ['nanh chatgpt-desktop', '<a href="https://openai.com/chatgpt/desktop/" target="_blank" rel="noreferrer">ChatGPT</a>', 'macOS, Windows, Linux (preview)'],
          ['nanh claude-desktop', '<a href="https://claude.ai/download" target="_blank" rel="noreferrer">Claude</a>', 'macOS, Windows, Linux (beta)'],
          ['nanh hermes-desktop', '<a href="https://hermes-agent.nousresearch.com/" target="_blank" rel="noreferrer">Hermes</a>', 'macOS, Windows, Linux'],
          ['nanh pen', '<a href="https://www.pen.dev/" target="_blank" rel="noreferrer">Pen</a>', 'macOS, Windows, Linux']
        ]],
        ['h3', 'Qué pasa al lanzar una'],
        ['p', 'nan-harness prepara una conexión temporal con NaN, lanza la app y la limpia cuando se cierra. No sustituye la app ni te desconecta; tu login, historial y ajustes permanecen intactos.'],
        ['p', 'ChatGPT y Hermes usan un perfil separado. Claude, Pen y Zed restauran la configuración anterior al cerrarse. Pen y Zed reciben todos los modelos de texto disponibles en tu cuenta de NaN mediante un gateway local privado, que también proporciona el resumen final de tokens.'],
        ['h3', 'Si un arranque se interrumpe'],
        ['p', 'Cierra la app y vuelve a lanzar el mismo comando con <code>--restore</code>. nan-harness restaura el estado registrado durante el arranque interrumpido.'],
        ['h3', 'Ejecuta Hermes o Pen directamente'],
        ['p', 'Hermes Desktop y Pen también admiten configuración para uso directo. Después, abre la app normalmente; nan-harness deja de intervenir. Los resúmenes de uso solo funcionan al lanzar mediante <code>nanh</code>. Pen debe reiniciarse por completo para recargar un catálogo modificado:'],
        ['codes', ['nanh config hermes-desktop', 'hermes desktop', 'nanh config pen', 'abre Pen normalmente']],
        ['note', '<strong>Si te interesan, pruébalas y cuéntanoslo.</strong> Tu experiencia como usuario —qué funciona, qué falla, qué echas en falta— es la mejor forma de ayudar a que estas integraciones se consoliden.']
      ]],
      ['search', 'BÚSQUEDA CON NAN-HARNESS', [
        ['p', 'nan-harness puede dar a tu agente una herramienta de búsqueda web con <a href="https://docs.searxng.org/" target="_blank" rel="noreferrer">SearXNG</a>. Es opcional: no se instala ni se contacta nada hasta que configuras un backend.'],
        ['h3', 'Configúrala'],
        ['table', ['Comando', 'Qué hace'], [
          ['nanh search setup --local', 'Instala un SearXNG privado en tu equipo. Necesita Python 3.10+ y <code>tar</code> (macOS, Linux, Windows x64).'],
          ['nanh search setup --docker', 'Ejecuta SearXNG en un contenedor de Docker.'],
          ['nanh search setup --url https://…', 'Usa un servidor SearXNG de tu confianza.']
        ]],
        ['code', 'nanh search setup --local'],
        ['p', 'nan-harness comprueba que el backend funciona antes de guardarlo. No se guardan credenciales de SearXNG.'],
        ['h3', 'Gestiónala'],
        ['table', ['Comando', 'Qué hace'], [
          ['nanh search status', 'Muestra el backend actual. Añade <code>--json</code> para scripts.'],
          ['nanh search disable', 'Desactiva la búsqueda. El backend sigue instalado.'],
          ['nanh search update', 'Actualiza un backend local o de Docker.'],
          ['nanh search remove', 'Elimina el backend que creó nan-harness y su configuración.']
        ]],
        ['h3', 'Cómo la usa tu agente'],
        ['p', 'Si tu agente ya tiene un proveedor de búsqueda, nan-harness no lo toca. Si no, añade su propia herramienta de búsqueda. Solo tienes que pedírselo: "busca en la web las últimas novedades de Rust".'],
        ['p', 'Sin backend, la herramienta responde con instrucciones para configurarlo.'],
        ['table', ['Flag', 'Qué hace'], [
          ['(por defecto)', 'Añade la búsqueda solo si el agente no tiene ninguna.'],
          ['--no-search', 'No la añade nunca.'],
          ['--force-search', 'La añade aunque el agente tenga otro proveedor. No disponible para Aider.']
        ]],
        ['codes', ['nanh claude --no-search', 'nanh cline --force-search']],
        ['p', 'En Pi y Prime Agent, cualquier extensión instalada con una herramienta <code>web_search</code> cuenta como proveedor.'],
        ['h3', 'En la configuración nativa'],
        ['p', '<code>nanh config &lt;harness&gt;</code> sigue las mismas reglas y conserva tu elección de <code>--no-search</code> o <code>--force-search</code> al hacer <code>--refresh</code>. <code>nanh config --status</code> la muestra.']
      ]],
      ['limits', 'PRESUPUESTO DE TOKENS Y CONTEXTO', [
        ['p', 'Dos opciones para mantener una sesión bajo control:'],
        ['code', 'nanh codex --session-max-tokens 10000000 --context 150000'],
        ['h3', 'Presupuesto de sesión'],
        ['p', '<code>--session-max-tokens</code> limita los tokens de entrada y salida de un arranque. Cuenta todas las peticiones, también la compactación y los modelos auxiliares.'],
        ['p', 'Al llegar al límite, el agente recibe un aviso y deja de hacer peticiones. Tu conversación se conserva: lanza de nuevo con un límite mayor y retómala.'],
        ['note', 'Las peticiones que ya están en marcha pueden terminar, así que el total puede quedar un poco por encima del límite.'],
        ['p', 'Necesita el gateway local, así que no funciona con <code>--no-chat-gateway</code>.'],
        ['h3', 'Contexto'],
        ['p', '<code>--context</code> fija aproximadamente cuántos tokens usa el agente antes de compactar la conversación. El agente puede compactar un poco antes.'],
        ['table', ['--context', 'Harnesses y apps'], [
          ['Compatible', 'Claude Code, Codex, OpenCode, Hermes Agent, Pi, Prime Agent, Oh My Pi, Qwen Code, Kimi Code, Aider, Goose, Hermes Desktop, Zed'],
          ['No compatible', 'DeepSeek Harness, OpenClaw, Cline, fx, ChatGPT, Claude, Pen']
        ]]
      ]],
      ['options', 'OPCIONES', [
        ['h3', 'Opciones del arranque recomendado'],
        ['table', ['Opción', 'Qué hace'], [
          ['--model &lt;id&gt;', 'Qué modelo usar esta vez.'],
          ['--session-max-tokens &lt;tokens&gt;', 'Limita los tokens que puede usar este arranque.'],
          ['--context &lt;tokens&gt;', 'Fija cuándo compacta el agente la conversación.'],
          ['--no-search / --force-search', 'Desactiva o fuerza la búsqueda de nan-harness.'],
          ['--allow-untested', 'Permite una versión de un harness de línea de comandos que no se puede leer. Las versiones nuevas de Desktop ya avisan y continúan; el flag se sigue aceptando por compatibilidad.'],
          ['--allow-unsupported', 'Ejecuta una versión anterior al mínimo compatible.']
        ]],
        ['h3', 'Comandos avanzados de configuración nativa'],
        ['table', ['Comando', 'Qué hace'], [
          ['nanh config &lt;harness&gt;', 'Escribe una configuración nativa reversible de NaN sin lanzar el harness.'],
          ['nanh config &lt;harness&gt; --status', 'Comprueba si su configuración gestionada está actualizada.'],
          ['nanh config &lt;harness&gt; --refresh', 'Actualiza la clave copiada, el catálogo de modelos y los valores gestionados.'],
          ['nanh config &lt;harness&gt; --remove', 'Quita la configuración gestionada y restaura valores anteriores seguros.']
        ]],
        ['h3', 'Otros comandos'],
        ['table', ['Comando', 'Qué hace'], [
          ['nanh doctor', 'Revisa todo y te dice cómo está.'],
          ['nanh doctor &lt;harness&gt;', 'Revisa un harness en detalle.'],
          ['nanh auth login', 'Guarda tu clave de NaN.'],
          ['nanh auth status', 'Te dice qué clave se está usando.'],
          ['nanh auth logout', 'Borra la clave guardada y permite retirar configuraciones que contienen una copia.'],
          ['nanh config --status', 'Muestra todas las configuraciones nativas gestionadas por nan-harness.'],
          ['nanh config --refresh-all', 'Actualiza todas las configuraciones nativas gestionadas.'],
          ['nanh config --remove-all', 'Elimina todas las configuraciones nativas gestionadas.'],
          ['nanh search setup', 'Configura la búsqueda web.'],
          ['nanh search status', 'Muestra la configuración de búsqueda.'],
          ['nanh update', 'Actualiza nan-harness a la última versión.'],
          ['nanh telemetry on|off', 'Activa o desactiva la telemetría anónima.'],
          ['nanh uninstall', 'Elimina nan-harness y todo lo que dejó puesto.'],
          ['nanh --help', 'La lista completa, en tu terminal.']
        ]]
      ]],
      ['help', 'AYUDA Y PRIVACIDAD', [
        ['h3', 'Solución de problemas'],
        ['p', 'Ejecuta <code>nanh doctor</code> para comprobar la conexión, los modelos disponibles, los harness instalados y las versiones antiguas.'],
        ['code', 'nanh doctor'],
        ['p', 'Ese informe se puede compartir: no incluye claves, rutas, prompts ni respuestas del modelo. El informe de un solo harness incluye la ruta del ejecutable, así que revísalo antes de compartirlo.'],
        ['code', 'nanh doctor claude'],
        ['h3', 'Avisos de versión'],
        ['p', 'Cada versión de nan-harness se prueba con versiones concretas de cada harness. Si la tuya es más nueva que la última probada, nan-harness avisa y continúa. Las versiones anteriores al mínimo requieren <code>--allow-unsupported</code>; si no se puede leer el número de versión, requiere <code>--allow-untested</code>.'],
        ['h3', 'Telemetría'],
        ['p', 'Apagada mientras no la enciendas. Si la activas, nan-harness puede enviar informes sanitizados de fallos de la CLI y los bridges, además de un evento mínimo de uso con un identificador aleatorio de instalación, su versión, el harness, la operación, el transporte, la familia del sistema operativo, la arquitectura y el entorno de destino. Nunca envía prompts, respuestas del modelo, argumentos, rutas, credenciales, nombres de usuario ni nombres de equipo. Un diagnóstico específico de un modelo puede incluir su identificador de NaN. Como en cualquier petición HTTPS, la infraestructura receptora puede observar los metadatos de red habituales.'],
        ['codes', ['nanh telemetry on', 'nanh telemetry off']],
        ['p', 'Nos sirve para saber qué harnesses necesitan atención. Al apagarla se detienen los eventos de uso y el envío automático de errores. Un error interactivo aún puede ofrecer un informe anónimo de un solo uso.'],
        ['h3', 'Desinstalar'],
        ['p', 'Pide confirmación, deshace todas las configuraciones que dejó en tus agentes, borra tu clave guardada y se quita de en medio. Si cambiaste a mano alguna de esas configuraciones, se detiene en vez de pisarte el trabajo.'],
        ['code', 'nanh uninstall']
      ]]
    ],
    guides: 'GUÍAS',
    cliReference: 'REFERENCIA CLI',
    getStartedSection: 'EMPEZAR',
    introduction: 'INTRODUCCIÓN',
    gettingStarted: 'PRIMEROS PASOS',
    examples: 'EJEMPLOS',
    agents: 'AGENTES',
    apps: 'LANDING',
    welcome: 'Bienvenido a nan-harness.',
    docsLede: 'Esta documentación explica la forma recomendada de ejecutar tus agentes de código con NaN mediante nan-harness, además de la configuración nativa avanzada para los agentes compatibles.',
    callout: '<strong>Para empezar</strong> Asegúrate de tener disponible localmente tu API key de NaN. La clave es personal y permanece en tu entorno.',
    gettingStartedText: 'Empieza con <code>nanh &lt;harness&gt;</code> para que nan-harness compruebe la compatibilidad, prepare la conexión y supervise el proceso. Usa la configuración nativa solo cuando necesites arrancar un harness compatible con su propio comando.',
    examplesText: 'La forma recomendada mantiene el enrutamiento del proveedor y su mantenimiento dentro de nan-harness. La configuración nativa avanzada escribe ajustes persistentes en un agente compatible.',
    whatNext: 'Qué hacer después',
    next: 'SIGUIENTE',
    copied: 'Copiado ',
    copiedStatus: 'Copiado al portapapeles.',
    telemetryCopiedStatus: 'Copiado al portapapeles. Gracias por ayudar a mejorar nan-harness.',
    copyFailed: 'No se pudo copiar. Inténtalo de nuevo.',
    faqs: [
      ['¿Qué es nan-harness?', `La forma recomendada de utilizar cualquier harness compatible con los modelos disponibles en tu ${nanLink('suscripción a la comunidad NaN')}. El comando completo del proyecto es <code>nan-harness</code>; <code>nanh</code> es su alias corto.`],
      ['¿Sustituye a mi agente?', 'No. Conservas el agente original, su perfil y sus flujos. nan-harness gestiona su arranque y la conexión con NaN sin reemplazar el cliente ni escribir ajustes persistentes del proveedor.'],
      ['¿Cuándo debería usar nanh config?', 'Úsalo solo cuando necesites arrancar un harness compatible mediante su comando habitual. Para el uso diario, recomendamos <code>nanh &lt;harness&gt;</code>; la configuración nativa debe actualizarse cuando cambien la clave guardada o el catálogo de modelos y no está disponible para Claude Code, Codex ni fx.'],
      ['¿Cómo se descubren los modelos?', '<code>nanh &lt;harness&gt;</code> consulta el catálogo actual de NaN al arrancar. La configuración nativa avanzada escribe una copia del catálogo en el harness, así que ejecuta <code>nanh config &lt;harness&gt; --refresh</code> cuando cambien tus modelos disponibles.'],
      ['¿Puedo pedir otro harness?', 'Sí. Si echas de menos algún harness, <a href="https://github.com/DavidLMS/nan-harness/issues/new" target="_blank" rel="noreferrer">abre un issue</a> e indícanos cuál te gustaría que incorporásemos.']
    ]
  };
}
