// English site copy for nan-harness. This classic script runs before
// app.js and only builds strings: it reads no DOM, storage, or navigator state.
// The caller passes every link and command the copy interpolates.
function nanHarnessContentEn({ harnessLink, nanLink, unixInstallCommand, windowsInstallCommand }) {
  return {
    siteTitle: 'nan-harness — run coding agents with NaN',
    siteMeta: 'Run supported coding agents with NaN through nan-harness.',
    docsTitle: 'nan-harness — docs',
    docsMeta: 'Documentation for running supported coding agents with NaN through nan-harness.',
    logosTitle: 'nan-harness — logo notices',
    logosMeta: 'Logo notices for nan-harness.',
    language: 'Language',
    homeAria: 'nan-harness home',
    mainNavigation: 'Main navigation',
    docsNavigation: 'Documentation navigation',
    breadcrumb: 'Breadcrumb',
    skipToContent: 'Skip to content',
    docs: 'DOCS',
    faq: 'FAQ',
    getStarted: 'GET STARTED',
    githubAria: 'Open nan-harness on GitHub',
    readDocs: 'READ THE DOCS',
    seeHarnesses: 'SEE SUPPORTED HARNESSES',
    heroTitle: 'ALL|HARNESSES|WITH NAN.',
    heroLede: `Run any supported coding agent with ${nanLink('NaN')} through nan-harness. One command checks compatibility, discovers your available models, prepares the connection, and supervises the process.`,
    whatIs: 'WHAT IS NAN-HARNESS',
    oneLocal: 'The model moves.',
    everyAgent: 'Your workflow stays.',
    whatText: 'NaN provides the models. Your agent provides the workflow. nan-harness connects them across every supported harness while you keep the client and workflow you already use.',
    howItWorks: 'SEE THE WORKFLOW',
    workflowLabel: 'THE RECOMMENDED WAY',
    discovering: '→ discovering harness',
    startingRoute: '→ starting local route',
    ready: '→ harness ready',
    workflowHeading: 'Run it through nan-harness.',
    workflowSubheading: 'One command.',
    workflowText: 'Use <code>nanh &lt;harness&gt;</code> for everyday launches. It checks compatibility, discovers your available NaN models, prepares any required bridge, and supervises the process. Use <code>nanh config &lt;harness&gt;</code> only when you need to start the harness directly; refresh that configuration when your saved key or model catalog changes.',
    workflowMode: 'recommended / advanced',
    managedLaunchResult: '→ recommended: checks, routes and supervises OpenCode',
    nativeSetupResult: '→ advanced: writes persistent OpenCode configuration',
    directLaunchResult: '→ direct launch: uses copied credentials and a model catalog',
    telemetryLabel: 'PRIVACY BY DESIGN',
    telemetryHeading: 'Telemetry off.',
    telemetrySubheading: 'Consent on.',
    telemetryCommand: 'nanh telemetry on',
    telemetryText: 'Telemetry is off by default. If enabled, nan-harness sends sanitized diagnostics and minimal usage data. It never includes prompts, model output, arguments, paths, or credentials. A model-specific diagnostic may include the NaN model ID.',
    telemetryPanelTitle: 'nanh telemetry',
    faqHeading: 'WORTH|KNOWING.',
    finalAgent: 'EVERY AGENT.',
    finalNan: 'NAN-ROUTED.',
    startDocs: 'START WITH THE DOCS',
    installLatest: 'INSTALL THE LATEST RELEASE',
    installCommand: unixInstallCommand,
    installWindowsCommand: windowsInstallCommand,
    installPlatform: 'Choose your operating system',
    unixTab: 'macOS / LINUX',
    windowsTab: 'WINDOWS',
    copy: 'Copy',
    chooseHarness: 'Choose a harness',
    oneRoute: 'ONE ROUTE · EVERY HARNESS',
    copyCommand: 'Copy command',
    copyingCommand: 'Copying command',
    commandCopied: 'Command copied',
    pauseCarousel: 'Pause automatic selection',
    resumeCarousel: 'Resume automatic selection',
    footerTagline: 'Every harness. Your favorite provider.',
    logoNotices: 'Logo notices',
    logosHeading: 'Harness logo notices',
    logosIntro: 'These assets identify supported third-party products. Their inclusion does not imply sponsorship, endorsement, or affiliation. Names and trademarks remain the property of their respective owners and are not covered by this repository\'s Apache-2.0 license.',
    logosSimpleIconsHeading: 'Simple Icons 16.28.0',
    logosSimpleIconsText: '<code>claude.svg</code>, <code>opencode.svg</code>, <code>pi.svg</code>, <code>deepseek.svg</code>, <code>cline.svg</code>, <code>qwen.svg</code>, and <code>kimi.svg</code> come from the <code>simple-icons</code> npm package version 16.28.0. Simple Icons releases its icon data under CC0-1.0. Its license and trademark disclaimer are included in <a href="logos/licenses/CC0-1.0.txt">licenses/CC0-1.0.txt</a> and <a href="logos/licenses/SIMPLE-ICONS-DISCLAIMER.md">licenses/SIMPLE-ICONS-DISCLAIMER.md</a>.',
    logosPackage: 'Package: <a href="https://www.npmjs.com/package/simple-icons/v/16.28.0" target="_blank" rel="noreferrer">simple-icons 16.28.0 on npm</a>',
    logosOfficialHeading: 'Official project sources',
    logosOfficialText: 'The remaining marks come from the official project sources below. They are included to identify the supported products.',
    logosTableHeaders: ['Asset', 'Source', 'Terms'],
    logosSources: [
      ['codex.png', '<a href="https://marketplace.visualstudio.com/items?itemName=OpenAI.chatgpt" target="_blank" rel="noreferrer">Official Codex VS Code extension 26.5818.31338</a>, using its <a href="https://openai.gallerycdn.vsassets.io/extensions/openai/chatgpt/26.5818.31338/1787264961823/Microsoft.VisualStudio.Services.Icons.Default" target="_blank" rel="noreferrer">published icon</a>', '<a href="https://openai.com/brand/" target="_blank" rel="noreferrer">OpenAI brand guidelines</a>; black background converted to transparency without changing the mark geometry'],
      ['hermes.png', '<a href="https://github.com/NousResearch/hermes-agent/blob/06b9141109fbd320b14b8c88645ab37fc4f42c9d/apps/desktop/assets/icon.png" target="_blank" rel="noreferrer"><code>NousResearch/hermes-agent</code> at <code>06b9141</code></a>', 'MIT; extracted from the locally installed desktop app and resized to 256 px without visual changes'],
      ['omp.svg', 'The official <a href="https://omp.sh/" target="_blank" rel="noreferrer"><code>omp.sh</code> header mark</a>, retrieved 2026-08-31', 'Used only for product identification; copied from the published header SVG without changing its geometry or colours'],
      ['prime.svg', '<a href="https://github.com/PrimeIntellect-ai/prime-agent/blob/c75a637b00d3b52762841e72efe92289a0d55b49/assets/brand/prime-butterfly.svg" target="_blank" rel="noreferrer"><code>PrimeIntellect-ai/prime-agent</code> at <code>c75a637</code></a>', 'MIT'],
      ['openclaw.svg', '<a href="https://github.com/openclaw/openclaw/blob/73ff2d2f45b26856882423d9ae87a76a727ac7cd/ui/public/favicon.svg" target="_blank" rel="noreferrer"><code>openclaw/openclaw</code> at <code>73ff2d2</code></a>', 'MIT'],
      ['aider.svg', '<a href="https://github.com/Aider-AI/aider/blob/5dc9490bb35f9729ef2c95d00a19ccd30c26339c/aider/website/assets/logo.svg" target="_blank" rel="noreferrer"><code>Aider-AI/aider</code> at <code>5dc9490</code></a>', 'Apache-2.0'],
      ['goose.svg', '<a href="https://github.com/aaif-goose/goose/blob/384b6cc0d3b52762841e72efe92289a0d55b49/documentation/static/img/goose.svg" target="_blank" rel="noreferrer"><code>aaif-goose/goose</code> at <code>384b6cc</code></a>', 'Apache-2.0'],
      ['fx.svg', 'The official <a href="https://fx.sh/" target="_blank" rel="noreferrer"><code>fx.sh</code> header mark</a>, associated with <a href="https://github.com/vercel-labs/fx/tree/580a0c5da9386319741968c09c1cee69e763487a" target="_blank" rel="noreferrer"><code>vercel-labs/fx</code> at <code>580a0c5</code></a>', 'Used only for product identification; the linked project repository is Apache-2.0; static glyph extracted without the website-only hover shimmer']
    ],
    logosLicenseText: 'The Apache-2.0 text is included in <a href="logos/licenses/APACHE-2.0.txt">licenses/APACHE-2.0.txt</a>. The applicable MIT notices are included as separate files: <a href="logos/licenses/MIT-hermes-agent.txt">MIT-hermes-agent.txt</a>, <a href="logos/licenses/MIT-openclaw.txt">MIT-openclaw.txt</a>, and <a href="logos/licenses/MIT-prime-agent.txt">MIT-prime-agent.txt</a>. The Codex mark is used only to identify the supported OpenAI product and remains subject to OpenAI\'s brand guidelines.',
    searchDocs: 'Search docs...',
    docsHeading: 'nan-harness',
    docsIntro: `Run the coding agents you already use with ${nanLink('NaN')} through nan-harness. Use <code>nanh &lt;harness&gt;</code> for everyday launches and <code>nanh config &lt;harness&gt;</code> only for advanced native setup. <code>nanh</code> is the shorter alias for <code>nan-harness</code>.`,
    docsNavStart: 'GET STARTED',
    docsNavReference: 'REFERENCE',
    docsSections: [
      ['install', 'INSTALL', [
        ['p', 'Run this on macOS or Linux:'],
        ['code', unixInstallCommand],
        ['p', 'On Windows, in PowerShell:'],
        ['code', windowsInstallCommand],
        ['p', 'If prompted, open a new terminal. Then verify the installation:'],
        ['code', 'nanh --version'],
        ['p', 'The installer provides both <code>nan-harness</code> and <code>nanh</code>. Release builds are available for macOS, Linux, and Windows. To build from source, see the <a href="https://github.com/DavidLMS/nan-harness">repository</a>.']
      ]],
      ['first-run', 'FIRST RUN', [
        ['p', 'Go to your project and launch the agent you already use:'],
        ['code', 'nanh claude'],
        ['p', 'If <code>NAN_API_KEY</code> is not set, nan-harness asks for your NaN API key the first time it needs one. It verifies and saves the key.'],
        ['p', 'After that, use the agent as usual. To choose a model at launch, use <code>--model</code>. If supported, you can also use the agent\'s native model picker:'],
        ['codes', ['nanh codex --model qwen3.6', 'nanh opencode --model deepseek-v4-flash']],
        ['p', 'Pass arguments to the agent after <code>--</code>; nan-harness forwards them unchanged:'],
        ['codes', ['nanh codex --model qwen3.6 -- --full-auto', 'nanh claude -- --resume']],
        ['h3', 'Your key'],
        ['note', '<strong>If you already have <code>NAN_API_KEY</code> in your environment, this section does not apply to you.</strong> That key wins over any other: nan-harness will not ask you for one, saves nothing to disk, and there is no need to log in.'],
        ['p', 'If you do not, nan-harness keeps it where your system keeps passwords: Keychain on macOS, Credential Manager on Windows, Secret Service on Linux. If none of them is available it uses a private file and warns you.'],
        ['table', ['Command', 'What it is for'], [
          ['nanh auth login', 'Enter a key, or replace the one you have.'],
          ['nanh auth status', 'See which key is in use and where it is stored.'],
          ['nanh auth logout', 'Delete the saved key.']
        ]],
        ['p', 'The environment variable is useful on servers and in CI. <code>nanh auth status</code> shows which credential is active:'],
        ['code', 'export NAN_API_KEY="<your-NaN-api-key>"'],
        ['note', '<strong>Keep your key private.</strong> The environment variable is never copied into a harness configuration.']
      ]],
      ['harnesses', 'HARNESSES', [
        ['p', '<code>nanh &lt;harness&gt;</code> is the recommended workflow for every supported harness. nan-harness checks the installed version, reads the current NaN catalog, prepares any required bridge and supervises the process without changing persistent provider settings. <code>nanh config &lt;harness&gt;</code> is an advanced option for harnesses that support direct native configuration.'],
        ['table', ['Recommended command', 'Harness', 'Native setup'], [
          ['nanh aider', harnessLink('Aider', 'aider'), 'optional'],
          ['nanh cline', harnessLink('Cline', 'cline'), 'optional'],
          ['nanh goose', harnessLink('Goose', 'goose'), 'optional'],
          ['nanh claude', harnessLink('Claude Code', 'claude'), 'not available'],
          ['nanh codex', harnessLink('Codex', 'codex'), 'not available'],
          ['nanh opencode', harnessLink('OpenCode', 'opencode'), 'optional'],
          ['nanh qwen', harnessLink('Qwen Code', 'qwen'), 'optional'],
          ['nanh pi', harnessLink('Pi', 'pi'), 'optional'],
          ['nanh kimi', harnessLink('Kimi Code', 'kimi'), 'optional'],
          ['nanh openclaw', harnessLink('OpenClaw', 'openclaw'), 'optional'],
          ['nanh hermes', harnessLink('Hermes Agent', 'hermes'), 'optional'],
          ['nanh omp', harnessLink('Oh My Pi', 'omp'), 'optional'],
          ['nanh prime-agent', harnessLink('Prime Agent', 'prime'), 'optional'],
          ['nanh dsh', harnessLink('DeepSeek Harness', 'deepseek'), 'optional'],
          ['nanh fx', harnessLink('fx', 'fx'), 'not available']
        ]],
        ['h3', 'Recommended: run with nan-harness'],
        ['p', 'For everyday use, run <code>nanh &lt;harness&gt;</code>. It checks the installed version, discovers your current NaN models, uses your current credential source, prepares any required bridge, and supervises the process. If the harness is missing, nan-harness can offer to install it.'],
        ['code', 'nanh opencode'],
        ['h3', 'Advanced: native setup'],
        ['p', 'Use <code>nanh config &lt;harness&gt;</code> only when another tool or integration needs to start a supported harness with its usual executable. Native setup writes persistent provider settings. The later launch runs directly through the harness, so nan-harness no longer manages that process. This command only configures the harness; start it afterwards with its usual executable:'],
        ['codes', ['nanh config opencode', 'opencode']],
        ['p', 'Claude Code, Codex and fx need nan-harness running because their NaN connection depends on a local bridge or gateway. They cannot be prepared for standalone use with <code>nanh config</code>.'],
        ['p', 'Native setup uses the API key saved by <code>nanh auth login</code>; an environment-only key is never copied into another application. Use <code>--status</code> to inspect it and <code>--refresh</code> after changing your saved key or model catalog. <code>--remove</code> removes what nan-harness added and restores previous settings when it is safe to do so.']
      ]],
      ['desktop', 'DESKTOP APPS (EXPERIMENTAL)', [
        ['p', 'These integrations are <strong>experimental</strong>. All five apps have been tested on macOS. Other platform combinations are covered by automated compatibility tests.'],
        ['table', ['Command', 'App', 'Available on'], [
          ['nanh zed', '<a href="https://zed.dev/" target="_blank" rel="noreferrer">Zed</a>', 'macOS, Windows, Linux'],
          ['nanh chatgpt-desktop', '<a href="https://openai.com/chatgpt/desktop/" target="_blank" rel="noreferrer">ChatGPT</a>', 'macOS, Windows, Linux (preview)'],
          ['nanh claude-desktop', '<a href="https://claude.ai/download" target="_blank" rel="noreferrer">Claude</a>', 'macOS, Windows, Linux (beta)'],
          ['nanh hermes-desktop', '<a href="https://hermes-agent.nousresearch.com/" target="_blank" rel="noreferrer">Hermes</a>', 'macOS, Windows, Linux'],
          ['nanh pen', '<a href="https://www.pen.dev/" target="_blank" rel="noreferrer">Pen</a>', 'macOS, Windows, Linux']
        ]],
        ['h3', 'What happens when you launch one'],
        ['p', 'nan-harness prepares a temporary NaN connection, launches the app, and cleans up when it closes. It does not replace the app or log you out; your login, history, and settings stay intact.'],
        ['p', 'ChatGPT and Hermes use a separate profile. Claude, Pen, and Zed restore their previous configuration when they close. Pen and Zed receive all text models available to your NaN account through a private local gateway, which also provides the final token-usage summary.'],
        ['h3', 'If a launch is interrupted'],
        ['p', 'Close the app and run the same command again with <code>--restore</code>. nan-harness restores the state recorded for the interrupted launch.'],
        ['h3', 'Run Hermes or Pen directly'],
        ['p', 'Hermes Desktop and Pen can also be configured for direct use. After that, open the app normally; nan-harness is no longer involved. Usage summaries work only when you launch through <code>nanh</code>. Pen must be fully restarted to reload a changed model catalog:'],
        ['codes', ['nanh config hermes-desktop', 'hermes desktop', 'nanh config pen', 'open Pen normally']],
        ['note', '<strong>If you are interested, try them and tell us.</strong> Your experience as a user — what works, what breaks, what you miss — is the best way to help make these integrations solid.']
      ]],
      ['search', 'SEARCH WITH NAN', [
        ['p', 'Many coding agents can search the web. When nan-harness launches one, it checks whether the agent already has a recognized search provider — in the agent, the project or its local search configuration. Only when it does not find one does it add NaN web search as a fallback. Your existing search settings are never touched.'],
        ['p', 'The agent sees it as a normal web-search tool, so you just ask it: "search the web for the latest Rust release notes", "look up how other people fixed this error", or "find the official docs for that library". The request goes through your NaN account like any other model call.'],
        ['h3', 'Override the selection'],
        ['table', ['Flag', 'What it does'], [
          ['(default)', 'Automatic: adds NaN search only if no other recognized provider is configured.'],
          ['--no-search', 'Never adds NaN web search for this launch, even without another provider.'],
          ['--force-search', 'Adds NaN web search even when another provider exists.']
        ]],
        ['codes', ['nanh claude --no-search', 'nanh cline --force-search']],
        ['p', 'For Pi and Prime Agent, the check also inspects the runtime tool inventory after installed package extensions load. Any package exposing a tool named <code>web_search</code> suppresses the NaN fallback on its own; <code>--force-search</code> gives the NaN tool precedence instead.'],
        ['h3', 'In native setup'],
        ['p', '<code>nanh config &lt;harness&gt;</code> applies the same policy. A chosen <code>--force-search</code> or <code>--no-search</code> is stored in the configuration receipt and kept on later <code>--refresh</code> runs unless you pass a new flag. <code>nanh config --status</code> shows the stored policy and whether the NaN fallback is active.'],
        ['p', 'For Pi, Oh My Pi and Prime Agent, native setup installs a runtime-aware extension rather than a search MCP entry; refreshing an older configuration migrates it automatically and preserves unrelated MCP servers. Aider supports native model configuration but not the NaN web search fallback.']
      ]],
      ['options', 'OPTIONS', [
        ['h3', 'Recommended launch options'],
        ['table', ['Option', 'What it does'], [
          ['--model &lt;id&gt;', 'Which model to use this time.'],
          ['--allow-untested', 'Allows a command-line harness version that cannot be read. Newer Desktop versions already warn and continue; the flag remains accepted for compatibility.'],
          ['--allow-unsupported', 'Runs a version below the supported minimum.']
        ]],
        ['h3', 'Advanced native setup commands'],
        ['table', ['Command', 'What it does'], [
          ['nanh config &lt;harness&gt;', 'Writes a reversible native NaN configuration without launching the harness.'],
          ['nanh config &lt;harness&gt; --status', 'Checks whether its managed configuration is current.'],
          ['nanh config &lt;harness&gt; --refresh', 'Updates the copied key, model catalog and managed defaults.'],
          ['nanh config &lt;harness&gt; --remove', 'Removes the managed configuration and restores safe previous values.']
        ]],
        ['h3', 'Other commands'],
        ['table', ['Command', 'What it does'], [
          ['nanh doctor', 'Checks everything and tells you how it looks.'],
          ['nanh doctor &lt;harness&gt;', 'Checks one harness in detail.'],
          ['nanh auth login', 'Saves your NaN key.'],
          ['nanh auth status', 'Tells you which key is in use.'],
          ['nanh auth logout', 'Deletes the saved key and lets you remove configurations that contain a copy.'],
          ['nanh config --status', 'Shows every native configuration managed by nan-harness.'],
          ['nanh config --refresh-all', 'Refreshes every managed native configuration.'],
          ['nanh config --remove-all', 'Removes every managed native configuration.'],
          ['nanh update', 'Updates nan-harness to the latest version.'],
          ['nanh telemetry on|off', 'Turns anonymous telemetry on or off.'],
          ['nanh uninstall', 'Removes nan-harness and everything it left behind.'],
          ['nanh --help', 'The full list, in your terminal.']
        ]]
      ]],
      ['help', 'HELP AND PRIVACY', [
        ['h3', 'Troubleshooting'],
        ['p', 'Run <code>nanh doctor</code> to check connectivity, model availability, installed harnesses, and stale versions.'],
        ['code', 'nanh doctor'],
        ['p', 'That report is safe to share: it excludes keys, paths, prompts, and model output. The single-harness report includes the executable path, so review it before sharing.'],
        ['code', 'nanh doctor claude'],
        ['h3', 'Version warnings'],
        ['p', 'Each release of nan-harness is tested against specific versions of each harness. If yours is newer than the last tested version, nan-harness warns you and continues. Older versions below the minimum require <code>--allow-unsupported</code>; versions whose number cannot be read require <code>--allow-untested</code>.'],
        ['h3', 'Telemetry'],
        ['p', 'Off unless you turn it on. If enabled, nan-harness can send sanitized CLI and bridge error reports plus a minimal invocation event with a random installation identifier, its version, the harness, operation, transport, OS family, architecture, and target environment. It never sends prompts, model output, arguments, paths, credentials, usernames, or hostnames. A model-specific diagnostic may include the NaN model ID. As with any HTTPS request, the receiving infrastructure can observe ordinary network metadata.'],
        ['codes', ['nanh telemetry on', 'nanh telemetry off']],
        ['p', 'It helps us see which harnesses need attention. Turning it off stops usage events and automatic error delivery. An interactive error may still offer a one-time anonymous report.'],
        ['h3', 'Uninstalling'],
        ['p', 'It asks for confirmation, undoes every configuration it left in your agents, deletes your saved key and removes itself. If you changed one of those configurations by hand, it stops instead of overwriting your work.'],
        ['code', 'nanh uninstall']
      ]]
    ],
    guides: 'GUIDES',
    cliReference: 'CLI REFERENCE',
    getStartedSection: 'GET STARTED',
    introduction: 'INTRODUCTION',
    gettingStarted: 'GETTING STARTED',
    examples: 'EXAMPLES',
    agents: 'AGENTS',
    apps: 'LANDING',
    welcome: 'Welcome to nan-harness.',
    docsLede: "This documentation explains the recommended way to run your coding agents with NaN through nan-harness, plus the advanced native-setup option for supported harnesses.",
    callout: '<strong>To get started</strong> Make sure your NaN API key is available locally. The key is personal and stays in your environment.',
    gettingStartedText: 'Start with <code>nanh &lt;harness&gt;</code> so nan-harness can check compatibility, prepare the connection and supervise the process. Use native setup only when you specifically need to start a compatible harness with its own command.',
    examplesText: 'The recommended workflow keeps provider routing and maintenance in nan-harness. Advanced native setup writes persistent settings into a compatible agent.',
    whatNext: 'What to do next',
    next: 'NEXT',
    copied: 'Copied ',
    copiedStatus: 'Copied to clipboard.',
    telemetryCopiedStatus: 'Copied to clipboard. Thanks for helping improve nan-harness.',
    copyFailed: 'Copy failed. Try again.',
    faqs: [
      ['What is nan-harness?', `The recommended way to use supported coding agents with models from your ${nanLink('NaN community subscription')}. The project command is <code>nan-harness</code>; <code>nanh</code> is its short alias.`],
      ['Does it replace my agent?', 'No. You keep the original agent, profile and workflows. nan-harness manages its launch and NaN connection without replacing the client or writing persistent provider settings.'],
      ['When should I use nanh config?', 'Use it only when you need to start a supported harness with its normal command. For everyday use, prefer <code>nanh &lt;harness&gt;</code>; native setup must be refreshed when your saved key or model catalog changes and is unavailable for Claude Code, Codex, and fx.'],
      ['How are models discovered?', '<code>nanh &lt;harness&gt;</code> reads the current NaN catalog at launch. Advanced native setup writes a catalog snapshot into the harness, so run <code>nanh config &lt;harness&gt; --refresh</code> when your available models change.'],
      ['Can I request another harness?', 'Yes. If a harness you use is missing, <a href="https://github.com/DavidLMS/nan-harness/issues/new" target="_blank" rel="noreferrer">open an issue</a> and tell us which one you would like to see supported.']
    ]
  };
}
